name: Build and deploy ASP.Net Core app to Azure Web App - bpprojectmaliha
env:
  URI: https://bpprojectmaliha.azurewebsites.net
  AZURE_WEBAPP_PACKAGE_PATH: 'publish'
  AZURE_WEBAPP_NAME: bpprojectmaliha
on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  build:                              #build job
    runs-on: ubuntu-latest            #running on ubuntu

    steps:
      - uses: actions/checkout@v3     #checking out code

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
        
       
       #install dependencies
      - name: Install dependencies      
        run: dotnet restore

      - name: Build with dotnet
        run: dotnet build --configuration Release
        
        
      - name: Run unit tests
        run: dotnet test bmiUnitTestProject/bmiUnitTestProject.csproj --no-restore --collect "Code coverage" -l:trx
     
        #publish unit test results
      - name: Publish Unit Test Results
        uses: dorny/test-reporter@v1
        with:
          artifact: ''
          name: MS Tests                  
          path: '**.trx'
          reporter: 'dotnet-trx' 
          
      - name: Publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

      - name: Run Azure webapp deploy action using publish profile credentials
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}         
          package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp'
